nameOverride: ""
fullnameOverride: ""

etcd:
  clusterNodeCount: 2
  replicaCount: 1
  peerPort: 2380
  clientPort: 2379

controlServer:
  replicaCount: 1
  clusterPort: 8080
  targetPort: 8080

simpleClient:
  desiredCount: 1
  replicaCount: 1
  clusterPort: 4747
  targetPort: 4747
