nameOverride: ""
fullnameOverride: ""

etcd:
  clusterNodeCount: 2
  replicaCount: 1
  peerPort: 2380
  clientPort: 2379

controlServer:
  replicaCount: 1
  containerPort: 8080

simpleClient:
  desiredCount: 1
  replicaCount: 1
  port: 4747
