---
apiVersion: v1
kind: Service
metadata:
  name: control-server
  namespace: zts-poc
spec:
  type: NodePort
  ports:
    - name: control-server-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: control-server
