---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  namespace: zts-poc
spec:
  type: NodePort
  ports:
    - name: etcd-client-port
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd
