---
apiVersion: v1
kind: Service
metadata:
  name: simple-client0
  namespace: zts-poc
spec:
  type: NodePort
  ports:
    - name: simple-client0-port
      port: 4747
      protocol: TCP
      targetPort: 4747
  selector:
    app: simple-client0
