---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "zts-poc.labels" . | indent 4 }}
  name: etcd-client
  namespace: {{ include "zts-poc.name" . }}
spec:
  type: NodePort
  ports:
    - name: etcd-client-port
      port: {{ .Values.etcd.clientPort }}
      protocol: TCP
      targetPort: {{ .Values.etcd.clientPort }}
  selector:
    app: etcd
