---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: control-server
{{ include "zts-poc.labels" . | indent 4 }}
  name: control-server
  namespace: {{ include "zts-poc.name" . }}
spec:
  replicas: {{ .Values.controlServer.replicaCount | int }}
  selector:
    matchLabels:
      app: control-server
  template:
    metadata:
      labels:
        app: control-server
    spec:
      initContainers:
        - name: wait-for-etcd
          image: busybox
          command: ["/bin/sh", "-c", "for URL in $(wget -q -O - http://etcd-client:2379/v2/members | tr ',' '\n' | sed -n -E 's/^.*client.*\"(htt[^\"]*?)\".*?$/\\1/p' | tr '\n' ' ' ); do while (wget -q -O - http://etcd1.zts-poc.svc:2379/health | awk '/true/{ exit(1) }'); do sleep 5; done; done"]
      containers:
        - image: wizardsoftheweb/zts-poc:control-server
          imagePullPolicy: Always
          name: control-server
          ports:
            - containerPort: {{ .Values.simpleClient.port }}
              name: http
              protocol: TCP
      restartPolicy: Always
