---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "zts-poc.labels" . | indent 4 }}
  name: control-server
  namespace: {{ include "zts-poc.name" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.controlServer.port }}
      protocol: TCP
      targetPort: {{ .Values.controlServer.port }}
  selector:
    app: control-server
